name: deploy-release

on:
    workflow_dispatch:
      inputs:
        release_version:
          description: "Release version"
          required: true

jobs:
  deploy:
    name: Deploy release
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YA_VM_PUBLIC_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Logging in to YC"
            sudo usermod -a -G docker $USER
            docker login --username oauth --password ${{ secrets.YA_CR_OAUTH_TOKEN }} cr.yandex

            docker kill $(docker ps -q)
            docker rm $(docker ps -a -q)
            docker run -d --restart unless-stopped -p 3000:3000 cr.yandex/${{secrets.YA_REGISTRY_ID}}/app:${{ inputs.release_version }}_latest

          
          

      


