name: deploy-release

on:
    workflow_dispatch:
      inputs:
        release_version:
          description: "Release version"
          required: true

jobs:
  deploy:
    name: Deploy release
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YA_VM_PUBLIC_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          scripts: |
            sudo groupadd docker
            sudo usermod -aG docker ${USER}
            echo ${{ secrets.YA_CR_OAUTH_TOKEN }} | docker login --username oauth --password-stdin cr.yandex

      


