name: deploy-release

on:
    workflow_dispatch:
      inputs:
        release_version:
          description: "Release version"
          required: true

jobs:
  deploy:
    name: Deploy release
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YA_VM_PUBLIC_IP }}
          username: shri-hw 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          

      


