name: release

on:
    workflow_dispatch:

jobs:
  lint:
    name: Run lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run lint

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run test

  create_release_branch:
    name: Create release branch
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
        - uses: actions/checkout@v4
        - name: Create release branch
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            RELEASE_BRANCH="releases/${{ github.run_number }}"
            git checkout -b $RELEASE_BRANCH
            git push origin $RELEASE_BRANCH

  build_docker_image:
    name: Build docker image
    runs-on: ubuntu-latest
    needs: [create_release_branch]
    steps:
      - uses: actions/checkout@v4

      - name: Yandex cloud auth
        run: docker login --username oauth --password ${{ secrets.YA_CR_OAUTH_TOKEN }} cr.yandex

      - name: Build docker image
        run: docker build . -t cr.yandex/${{ secrets.YA_REGISTRY_ID }}/app:${{ github.run_number }}

      - name: Tag docker image
        run: docker build . -t cr.yandex/${{ secrets.YA_REGISTRY_ID }}/app:${{ github.run_number }}  

      - name: Push docker image
        run: |
          docker push cr.yandex/${{ secrets.YA_REGISTRY_ID }}/app:${{ github.run_number }}
          docker push cr.yandex/${{ secrets.YA_REGISTRY_ID }}/app:${{ github.run_number }}_latest
